#include "patch_internal.hpp"

namespace LunaAGPatch
{
HMODULE g_module = nullptr;
HMODULE g_pinnedModule = nullptr;
std::wstring g_moduleDir;
std::wstring g_logPath;
std::wstring g_windowsDir;
std::vector<RedirectRule> g_rules;
std::vector<ResolvedHost> g_resolvedHosts;
std::unordered_map<HINTERNET, std::wstring> g_winHttpRequestPaths;
std::unordered_set<void*> g_patchedLoginModules;
std::mutex g_mutex;
std::recursive_mutex g_inlineHookMutex;
bool g_enabled = true;
bool g_logEnabled = true;
bool g_consoleEnabled = true;
bool g_consoleReady = false;
bool g_patchImports = false;
bool g_logAllConnects = true;
bool g_logAllDns = true;
bool g_patchAllNonSystem = true;
bool g_keepAlive = true;
bool g_uiPatch = true;
bool g_forceLoginCallback = true;
bool g_inlineHooks = true;
bool g_initialized = false;
bool g_logCleared = false;
DWORD g_lastPatchTick = 0;
DWORD g_lastUiPatchTick = 0;
std::wstring g_captchaFlagPath;
std::wstring g_forceLoginFlagPath;
ConnectFn g_connect = nullptr;
WsaConnectFn g_wsaConnect = nullptr;
WsaIoctlFn g_wsaIoctl = nullptr;
ConnectExFn g_connectEx = nullptr;
GetAddrInfoFn g_getaddrinfo = nullptr;
GetAddrInfoWFn g_getaddrinfoW = nullptr;
GetProcAddressFn g_getProcAddress = nullptr;
WinHttpConnectFn g_winHttpConnect = nullptr;
WinHttpOpenRequestFn g_winHttpOpenRequest = nullptr;
WinHttpSendRequestFn g_winHttpSendRequest = nullptr;
Il2CppDomainGetFn g_il2cppDomainGet = nullptr;
Il2CppThreadAttachFn g_il2cppThreadAttach = nullptr;
Il2CppDomainGetAssembliesFn g_il2cppDomainGetAssemblies = nullptr;
Il2CppAssemblyGetImageFn g_il2cppAssemblyGetImage = nullptr;
Il2CppClassFromNameFn g_il2cppClassFromName = nullptr;
Il2CppClassGetTypeFn g_il2cppClassGetType = nullptr;
Il2CppTypeGetObjectFn g_il2cppTypeGetObject = nullptr;
Il2CppClassGetMethodFromNameFn g_il2cppClassGetMethodFromName = nullptr;
Il2CppClassGetFieldFromNameFn g_il2cppClassGetFieldFromName = nullptr;
Il2CppFieldGetOffsetFn g_il2cppFieldGetOffset = nullptr;
Il2CppRuntimeInvokeFn g_il2cppRuntimeInvoke = nullptr;
Il2CppStringNewFn g_il2cppStringNew = nullptr;
Il2CppArrayLengthFn g_il2cppArrayLength = nullptr;
Il2CppObjectNewFn g_il2cppObjectNew = nullptr;
void* g_loginModuleClass = nullptr;
void* g_unityObjectClass = nullptr;
void* g_inputFieldClass = nullptr;
void* g_loginResultClass = nullptr;
void* g_userInfoClass = nullptr;
void* g_logoffApplyClass = nullptr;
void* g_findObjectsOfTypeMethod = nullptr;
void* g_textSetTextMethod = nullptr;
void* g_geetestVerifyCallbackMethod = nullptr;
void* g_innerLoginCallbackMethod = nullptr;
void* g_loginResultCtorMethod = nullptr;
void* g_userInfoCtorMethod = nullptr;
void* g_logoffApplyCtorMethod = nullptr;
bool g_pendingCaptchaBypass = false;
bool g_pendingForceLoginCallback = false;
bool g_forceLoginCallbackDone = false;
Il2CppFieldOffsets g_offsets;
bool g_offsetsResolved = false;
InlineHook g_connectInlineHook;
InlineHook g_wsaConnectInlineHook;
InlineHook g_wsaIoctlInlineHook;
}
